import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="overflow-y-scroll" lang="en">
      <body className="bg-[#050505] max-w-7xl mx-auto">
        <main>
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
